# Generated by Django 5.2 on 2025-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalityresult',
            name='column_stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityresult',
            name='personality_type',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalityresult',
            name='raw_e_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityresult',
            name='raw_f_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityresult',
            name='raw_i_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityresult',
            name='raw_j_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityresult',
            name='raw_n_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityresult',
            name='raw_p_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityresult',
            name='raw_s_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityresult',
            name='raw_t_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('assessment', 'question')},
        ),
    ]
