# Generated by Django 5.2 on 2025-04-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
