# Generated by Django 5.1.4 on 2025-04-05 11:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='career_library/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='career_categories/')),
                ('card_count', models.PositiveIntegerField(default=0)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='career_site.careerlibrary')),
            ],
        ),
        migrations.CreateModel(
            name='CareerSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('daily_tasks', models.TextField(help_text='Bullet points separated by newlines')),
                ('image', models.ImageField(blank=True, null=True, upload_to='career_subcategories/')),
                ('current_demand', models.IntegerField(help_text='1=Extremely Low, 7=Extremely High', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('long_term_demand', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('very_long_term_demand', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='career_site.careercategory')),
            ],
        ),
        migrations.CreateModel(
            name='TopInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('is_private', models.BooleanField(default=True)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='career_site.careersubcategory')),
            ],
        ),
    ]
