# Generated by Django 5.2 on 2025-04-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityresult',
            name='assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='career_site.assessment'),
        ),
    ]
