# Generated by Django 5.1.4 on 2025-04-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_site', '0002_careerlibrary_careercategory_careersubcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Master Class Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MasterClassVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(help_text='YouTube video ID (11 characters)', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='career_site.masterclasscategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
