# Generated by Django 5.2 on 2025-04-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_site', '0003_userresponse_delete_careerassessmentresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResponse',
            new_name='OrientationAssessmentResponse',
        ),
    ]
