# Generated by Django 5.1.4 on 2025-04-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_site', '0003_masterclasscategory_masterclassvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerlibrary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='career_site/career_library'),
        ),
    ]
