# Generated by Django 5.2 on 2025-04-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_site', '0002_alter_personalityresult_assessment'),
        ('career_site', '0003_populate_assessment_field'),
    ]

    operations = [
    ]
