# Generated by Django 5.2 on 2025-04-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_site', '0004_rename_userresponse_orientationassessmentresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orientationassessmentresponse',
            name='user_id',
        ),
    ]
